package github

const (
	PermissionRead  ClientPermissionType = "read"
	PermissionWrite ClientPermissionType = "write"
	PermissionAdmin ClientPermissionType = "admin"

	PermissionActions                                ClientPermissionScope = "actions"
	PermissionAdministration                         ClientPermissionScope = "administration"
	PermissionChecks                                 ClientPermissionScope = "checks"
	PermissionCodeSpaces                             ClientPermissionScope = "codespaces"
	PermissionContents                               ClientPermissionScope = "contents"
	PermissionDependabotSecrets                      ClientPermissionScope = "dependabot_secrets"
	PermissionDeployments                            ClientPermissionScope = "deployments"
	PermissionEnvironments                           ClientPermissionScope = "environments"
	PermissionIssues                                 ClientPermissionScope = "issues"
	PermissionMetadata                               ClientPermissionScope = "metadata"
	PermissionPackages                               ClientPermissionScope = "packages"
	PermissionPages                                  ClientPermissionScope = "pages"
	PermissionPullRequests                           ClientPermissionScope = "pull_requests"
	PermissionRepositoryCustomProperties             ClientPermissionScope = "repository_custom_properties"
	PermissionRepositoryHooks                        ClientPermissionScope = "repository_hooks"
	PermissionRepositoryProjects                     ClientPermissionScope = "repository_projects"
	PermissionSecretScanningAlerts                   ClientPermissionScope = "secret_scanning_alerts"
	PermissionSecurityEvents                         ClientPermissionScope = "security_events"
	PermissionSingleFile                             ClientPermissionScope = "single_file"
	PermissionStatuses                               ClientPermissionScope = "statuses"
	PermissionVulnerabilityAlerts                    ClientPermissionScope = "vulnerability_alerts"
	PermissionWorkflows                              ClientPermissionScope = "workflows"
	PermissionMembers                                ClientPermissionScope = "members"
	PermissionOrganizationAdministration             ClientPermissionScope = "organization_administration"
	PermissionOrganizationCustomRoles                ClientPermissionScope = "organization_custom_roles"
	PermissionOrganizationCustomOrgRoles             ClientPermissionScope = "organization_custom_org_roles"
	PermissionOrganizationCustomProperties           ClientPermissionScope = "organization_custom_properties"
	PermissionOrganizationCopilotSeatManagement      ClientPermissionScope = "organization_copilot_seat_management"
	PermissionOrganizationAnnouncementBanners        ClientPermissionScope = "organization_announcement_banners"
	PermissionOrganizationEvents                     ClientPermissionScope = "organization_events"
	PermissionOrganizationHooks                      ClientPermissionScope = "organization_hooks"
	PermissionOrganizationPersonalAccessTokens       ClientPermissionScope = "organization_personal_access_tokens"
	PermissionOrganizationPersonalAccessTokenRequest ClientPermissionScope = "organization_personal_access_token_requests"
	PermissionOrganizationPlan                       ClientPermissionScope = "organization_plan"
	PermissionOrganizationProjects                   ClientPermissionScope = "organization_projects"
	PermissionOrganizationPackages                   ClientPermissionScope = "organization_packages"
	PermissionOrganizationSecrets                    ClientPermissionScope = "organization_secrets"
	PermissionOrganizationSelfHostedRunners          ClientPermissionScope = "organization_self_hosted_runners"
	PermissionOrganizationUserBlocking               ClientPermissionScope = "organization_user_blocking"
	PermissionTeamDiscussions                        ClientPermissionScope = "team_discussions"
	PermissionEmailAddresses                         ClientPermissionScope = "email_addresses"
	PermissionFollowers                              ClientPermissionScope = "followers"
	PermissionGITSSHKeys                             ClientPermissionScope = "git_ssh_keys"
	PermissionGPGKeys                                ClientPermissionScope = "gpg_keys"
	PermissionInteractionsLimits                     ClientPermissionScope = "interaction_limits"
	PermissionProfile                                ClientPermissionScope = "profile"
	PermissionStarring                               ClientPermissionScope = "starring"
)
